"use strict";
const bcrypt = require("bcryptjs");

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("users", [
      {
        name: "Tianah",
        email: "tianah@example.com",
        password: await bcrypt.hash("love1", 10),
        phone: "+250788123001",
        role: "couple",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Bruce",
        email: "bruce@example.com",
        password: await bcrypt.hash("love2", 10),
        phone: "+250788123002",
        role: "couple",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Faye",
        email: "faye@example.com",
        password: await bcrypt.hash("love3", 10),
        phone: "+250788123003",
        role: "couple",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "David",
        email: "david@example.com",
        password: await bcrypt.hash("love4", 10),
        phone: "+250788123004",
        role: "couple",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ivy",
        email: "ivy@example.com",
        password: await bcrypt.hash("love5", 10),
        phone: "+250788123005",
        role: "couple",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Willy",
        email: "willy@example.com",
        password: await bcrypt.hash("love6", 10),
        phone: "+250788123006",
        role: "couple",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Admin User",
        email: "admin@lumina.com",
        password: await bcrypt.hash("admin123", 10),
        phone: "+250788123007",
        role: "admin",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Umucyo Photography",
        email: "umucyo@photography.rw",
        password: await bcrypt.hash("vendor1", 10),
        phone: "+250788123008",
        role: "vendor",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Glow by Clarisse",
        email: "clarisse@glow.rw",
        password: await bcrypt.hash("vendor2", 10),
        phone: "+250788123009",
        role: "vendor",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kigali Heights Venue",
        email: "info@kigaliheights.rw",
        password: await bcrypt.hash("vendor3", 10),
        phone: "+250788123010",
        role: "vendor",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Africana Catering",
        email: "info@africana.rw",
        password: await bcrypt.hash("vendor4", 10),
        phone: "+250788123011",
        role: "vendor",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kigali Entertainment",
        email: "info@kigalientertain.rw",
        password: await bcrypt.hash("vendor5", 10),
        phone: "+250788123012",
        role: "vendor",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Elegant Weddings",
        email: "info@elegantweddings.rw",
        password: await bcrypt.hash("vendor6", 10),
        phone: "+250788123013",
        role: "vendor",
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("users", null, {});
  },
};
