"use strict";

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("vendors", [
      {
        userId: 8,
        businessName: "Umucyo Photography",
        vendorType: "photographer",
        description: "Award-winning wedding photographer capturing authentic moments in Kigali",
        priceRange: "$$$",
        city: "Kigali",
        address: "KG 541 St, Kigali Heights",
        website: "www.umucyophotography.rw",
        rating: 4.9,
        totalReviews: 124,
        isApproved: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 9,
        businessName: "Glow by Clarisse",
        vendorType: "makeup_artist",
        description: "Expert makeup artistry for weddings and special events",
        priceRange: "$$",
        city: "Kigali",
        address: "KN 82 St, Kigali",
        website: "www.glowbyclarisse.rw",
        rating: 4.8,
        totalReviews: 89,
        isApproved: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 10,
        businessName: "Kigali Heights Venue",
        vendorType: "venue",
        description: "Luxury wedding venue with stunning city views",
        priceRange: "$$$$",
        city: "Kigali",
        address: "KG 2 Ave, Kigali",
        website: "www.kigaliheights.rw",
        rating: 4.7,
        totalReviews: 156,
        isApproved: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 11,
        businessName: "Africana Catering",
        vendorType: "catering",
        description: "Delicious Rwandan and international cuisine for weddings",
        priceRange: "$$$",
        city: "Kigali",
        address: "KN 3 Rd, Kigali",
        website: "www.africanacatering.rw",
        rating: 4.8,
        totalReviews: 203,
        isApproved: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 12,
        businessName: "Kigali Entertainment",
        vendorType: "musician",
        description: "Professional DJ and live music services for weddings",
        priceRange: "$$",
        city: "Kigali",
        address: "KG 5 Ave, Kigali",
        website: "www.kigalientertain.rw",
        rating: 4.7,
        totalReviews: 178,
        isApproved: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 13,
        businessName: "Elegant Weddings",
        vendorType: "planner",
        description: "Full wedding planning and coordination services",
        priceRange: "$$$",
        city: "Kigali",
        address: "KG 8 St, Kigali",
        website: "www.elegantweddings.rw",
        rating: 4.9,
        totalReviews: 145,
        isApproved: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("vendors", null, {});
  },
};